# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  - package-ecosystem: "gradle"
    # Enable version updates for Gradle
    # Look for `build.gradle`  files in the `root` directory
    directory: "/"
    target-branch: "dep/dependency_upgrade_staging"
    open-pull-requests-limit: 20
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "America/Los_Angeles"
  - package-ecosystem: "github-actions"
    # Look for changes in github actions
    directory: "/"
    target-branch: "dep/dependency_upgrade_staging"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "America/Los_Angeles"
