language: java
jdk:
- openjdk8
cache:
  directories:
  - "$HOME/.m2"
after_success:
- "./gradlew cobertura coveralls --stacktrace"
- test "${TRAVIS_PULL_REQUEST}" == "false" && test "${TRAVIS_TAG}" != "" && ./gradlew
  bintrayUpload --stacktrace
env:
  global:
  - secure: LQy3Z6osgiB10IT6HjUyMidA3QSO1dy7GalCy5wT6inGBmAto9Q92nQzk1CnIsFEebvayaephuzhqYTxs3xT8ZPv8VmVk5p2eceiRY8K+KrHcPIMqkbESOyoXJWpv5DWv6dsyOazdYdh9GQJBN4y3/dvJOAhSkMGSpZGv85T36EWmTS2Zhc5G/ZyibEMGHfhQ4AMMHIHUHsTVgca+T2ddaDmjrDJwAXmE4MYLhGn2PexRfzFuAVJMl14ZMwkwJD6qExWpKZ7jq5SnvHWIahiofVScimCPdKg8LwoaexV96wUNOTzkkNlWZYyqMoSAGZLlBW5h8XyXtbPjPqViYR4ocDOwdyK7A38xU6jH9G9E41VqqwZk3ny4sujgti1OrxMOAieZA4jQE3gL1H11soJM4sZlg53yw5yZGaiR033xbZ/QMrjG3V1F6pBNW9UBZZh9uFgDTgqUU8z41QEHsCZBG6cWEIIZPFhHloampQtOkdFEoCifzuR4hKLacibHVlLOXG00H6sQvtszXE7yy1mHTX9YJn3hSVHarKprmbLfEsliPFscrwJvohj2y49umhgVtmbmrs94tS8MUm1S56GmBoyIcu66DkJ+AGWxJ0lS65xUoGM3y0hGOyGvrh8q0lDZdrFw5gtTpYhNCozHSxRx79v30ZCVGGpPq+LWONGR7U=
  - secure: Dk11Yrq0XT+VXXncqhyV+g0PDV+teFWobAigDpsncNKFtSth37Eoi6lrPVKT9S5b5qh+SVx7h7D3VSpMPoIAXuaeG62yn7e1RegCFk19xJB8aGsooVhwdlQk8yiCHe/1ITr6C95Ftj4QQT1k29inAsjvAqLPU229EwN+In4nAZw2S8qMR27FqCd6HvdrbwaM5PYVHvgANgBkL3awMmIm4On5wSqOdOukj8L7LztUA87YKfgUsOln1ERI+nN6fbN0FYdTFEWwG56HNhNvOSv5Gt3os92r47r0VFghIRrJOjwEWE2KFsEs43DYemrJBlgu0OCvk9A3gYr0vUeVxgT6LH5zZUTavK2ew6sZmUBpJLag9oezC1mjp3c8s90eRZX5eCaJ0Dyt4us9z3B96SEHg3lF3PZDq0xloeuxa8dgJp4HJzQi7HNn8sMezFE2DMeZ2x1zOuNbyiI6ZmDMCp54me1Z7MOk+MCu6q/8JAPpfEeaFPNVt5qYolI0pYzHURU1RVMzVN2sSaFMEnyBR6W/f5MoIHYGZFBygTPHZVgjkdpniKS+Meo6RrmXyrmDQMAc08bDjdepiQO51QP8h5BKXKkTrIa13XvOpVGkmbfBzoYC6RzVRZkovERQh2DSqMG+vclnDFzcBZ8xEqesAEp2c8tlSamTLu6wyeC0gi0VAxo=
