language: java
jdk:
- oraclejdk7
cache:
  directories:
  - "$HOME/.m2"
after_success:
- ./gradlew cobertura coveralls --stacktrace
- test "${TRAVIS_PULL_REQUEST}" == "false" && test "${TRAVIS_TAG}" != "" && ./gradlew
  bintrayUpload --stacktrace
env:
  global:
  - secure: UgLX22LNauPSfwCHpVXMaJ8mxH/5rCLS8pZn9L9ZS8DK/ig1tdAeauObFMXcFYJVpbKviRS7Dy5K8IjH8aZ4n26hd7JeOn7OzYEGs77XNqTqQk8mLR9o04Gp0sz/zAgQ1YGp2khHLxzkVmU95qrXnnsU6RvY3al3/qyvyvPEZaU8o0UERDcEE76rTMhjQLYC13x7Fj7uSOIZkFhvU0CEY4s7ldbhgdzJdah5wSmK1/qgLlgZ7GqSZGJkFMjJo+ur5qNflzfRwlrTpPJJaU0egQBZ9Xs1UR2b5uvr0oL+YwtVB8xwFRnQ5GexquZPSmcmEQM+TbggIAka6EKbougHMNVA1a5x18I+T/dVfrQnRHGApdRIGMmyU97Y/Cdx4Ofl8uQifht2QaF02UCTzlkrOpQk8HenzfwBxKBX02vyoYecSfbHptSmtauj2eX9f6XI/QFaF0pEdxRpP3Z8QfPwb5tefCRGP/6dHT32dFsWnaqdHnltSS8ztZwFLk08TR0zz9Mxft1aoVZr5F+rcRStvZNl97+HAlfoa5N6uc1GsLq6wSicw0cOacJzmmrHpF5gNhNiW5k7+P3qFK3hphMm1YozsOldyIDYA/MJPpQOdUr7oXI/KFtyg1696zjiRpCI7HJjrOgXAl1fRPvmJJf9WlbS61PJ/LAZZRF7kPbJhRE=
  - secure: NdEYXtXco6hBcgYkw690wFQa/4wmJiZfHIh2e7khAWVpojEqMSvDo66PbpYR9JJw6jsgDrx3SQd8M6JmKag74vmW88m9YxY6m/+48m8mSJ6nghrSLoIH9KyLEsxMRbTD1sQS5xY0XX/3HmVH4fPoCJPM7rf4Lj+sdNbNqsZ1A0psb2l9z9AuirJJDQkw8G07cpd1Xc+0ev78rY830LX4cAW/T/EfO5OhsHxKAuWwYcU9XK+gBMw+Gl9bbh1UZezOM9Rupyvxz5KaYNlXbW/tdKwJeM9NyopxZG9z94AyJluCmyR3DiXE+vGEFBpYnX3rS/gDPddHfLaNX/CDGH154YrIAgxcCs4uPMREZmM1DPUlJdl/B9DR/BQf4LrUnUKUqk8lFk2XGjnJfSuBtW/9IlbhfHO/I4ntIT3Rz1cl6OF+Vtqzm3hYfeVDCpQTAVjfgmWynbmG3VnZNgp18DTn1mj2XH7e6zTzj5ulPi4suAFAAqbX12/aQT/8w1Q7A3ZuC/vr8IjNM620a7rrrYWCvEU58nY0xMZ1fdJgtO8jk4jDhnoAVjFr+mi0lPyXVGmUEgYAhvAqNUUiu42v3KReSL4FdF2gaB2k7m7aEJtr3Mq8roy2T7Iu8ZYDi+i6I/8wtVs29U0iygX7eXKplXRDEv49uZqs4slD5yTkS4Jz9dM=
