language: java
jdk:
- openjdk8
cache:
  directories:
  - "$HOME/.m2"
after_success:
- ./gradlew cobertura coveralls --stacktrace
- test "${TRAVIS_PULL_REQUEST}" == "false" && test "${TRAVIS_TAG}" != "" && ./gradlew
  bintrayUpload --stacktrace
env:
  global:
