# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 22 * * 1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: corretto
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew assemble
      - name: Test with Gradle
        run: ./gradlew check
      - name: Upload coverage report to CodeCov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          file: ./build/reports/cobertura/coverage.xml # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true
      - name: Slack notification when master build fails
        if: ${{ failure() && github.ref == 'refs/heads/master'}}
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: cerberus-alerts
          SLACK_MESSAGE: 'Cerberus Java Client main build has failed on github :build-failed:'
          SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          SLACK_TITLE: Cerberus Java Client Build Failure Notification
          SLACK_USERNAME: GitHub Actions
